version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: mortgage-calculator-container
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        command: php -S 0.0.0.0:8000 -t public
        ports:
            - "8000:8000"
