version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php82-container
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: php -a
    tty: true
    ports:
      - "9000:9000"
